name: Learn basic of GitHub Action
on:
  push:
    branches:
      -  main
env: 
  JDK_VERSION: "openjdk11-jdk"      
jobs:  
  install-java:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: install java
        run: |
         apk add --no-cache $JDK_VERSION
         java --version
         echo "MAVEN_VERSION=1234" >>  $GITHUB_ENV

      - name: print maven version
        run: echo $MAVEN_VERSION

  print-env:
     runs-on: ubuntu-latest
     container: 
       image: alpine:latest
     steps:
       - name : print env
         run: echo $JDK_VERSION

  print-maven-version:
       runs-on: ubuntu-latest
       steps:
         - name: print maven version
           run : echo $MAVEN_VERSION
       
        
     
     
        
